[project]
name = "chat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.2",
    "ddgs>=9.8.0",
    "duckduckgo-search>=8.1.1",
    "json-repair>=0.54.3",
    "langchain>=1.0.5",
    "langchain-community>=0.4.1",
    "langchain-google-genai>=3.0.1",
    "langchain-openai>=1.0.2",
    "langchain-text-splitters>=1.0.0",
    "langgraph-cli[inmem]>=0.4.7",
    "peft==0.13.2",
    "torch>=2.9.1",
    "transformers==4.53.1",
    "accelerate>=1.0.1",
    "trl>=0.11.0",
    "modelscope>=1.33.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
